version: '3.8'

services:
  auth:
    image: docker.io/your-dockerhub-username/video-streaming-auth:latest
    ports: ["3000:3000"]
    environment:
      DB_HOST: mysql

  upload:
    image: docker.io/your-dockerhub-username/video-streaming-upload:latest
    ports: ["3001:3000"]
    volumes:
      - upload_temp:/app/temp-uploads 
    environment:
      DB_HOST: mysql
      AUTH_SERVICE: "http://auth:3000"

  streaming:
    image: docker.io/your-dockerhub-username/video-streaming-streaming:latest
    ports: ["3002:3000"]
    environment:
      DB_HOST: mysql

  file-service:
    image: docker.io/your-dockerhub-username/video-streaming-file-service:latest
    ports: ["3003:3000"]
    volumes:
      - uploaded_videos:/app/uploads

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videodb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  uploaded_videos:
  upload_temp:
